apiVersion: v1
kind: Pod
metadata:
  name: melodia-salsa
  namespace: salsa
  annotations:
    student-name: "Sebastián Marulanda"
    favorite-music: "Salsa"
spec:
  containers:
  - name: salsero
    image: nginx
  tolerations:
  - key: "music"
    operator: "Equal"
    value: "sabor-latino"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: style
            operator: In
            values:
              - latino
